services:
  - type: web
    name: controle-salas
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: /opt/render/project/venv/bin/gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
